### ISSUE TITLE
Assets Import Error

### ISSUE THREAD

**Issue by Longtianmu** [UnderLogic/toml-serialization#22]
I used custom registry to add the package into my Unity 2021 LTS.
But I keep met this error:
`Asset Packages/com.underlogic.toml-serialization/Tests/Runtime/Fixtures/EquipmentItem.cs has no meta file, but it's in an immutable folder. The asset will be ignored.`

**Comment by ewrogers** [comment]
Just released `v0.4.10` which should fix this issue. Sorry about that. Let me know if it resolves the issue.

**Comment by Longtianmu** [comment]
﻿
Thanks, by the way I wonder if there is any way to serialize GameObject into toml format?

在 2023年5月1日，15:12，Erik Rogers ***@***.***> 写道：

﻿

Just released v0.4.10 which should fix this issue. Sorry about that. Let me know if it resolves the issue.

**Comment by ewrogers** [comment]
No, and by design. I would not recommend trying to deserialize a `GameObject` itself, but rather the properties that are important to you, and then re-create that object in code when you need to deserialize.

A common use-case for serialization are game settings, player save, or level/scripted data. These should be serialized into some intermediary model that's not related to a `GameObject` instance.

In fact, there are things that `ScriptableObject` instances are perfect for. They are essential game objects which are not bound to a specific scene. Which all of the above mentioned things are perfectly suitable for. Basically, if it is something that a singleton Manager class is usually responsible for, you should look into `ScriptableObjects`.

Ryan Hipple has a [great Unity 2017 talk](https://www.youtube.com/watch?v=raQ3iHhE_Kk) about using SO's for things like this.

So let's assume you wanted to store settings like video resolution, audio volume, UI scale, or whatever else that's related to some kind of "user option" for your game.

1. Design a `ScriptableObject` named `GameSettings` with all the fields you want.
2. Design a `GameSettingsManager` component that can be put into a scene
3. Add a `SerializedProperty` that you can drag & drop the `GameSettings` SO into
4. On startup, deserialize the `settings.toml` into `GameSettings` SO
5. Since it is a SO, all references to it will also see these updates
6. Access the `GameSettingsManager` container component from your game
7. On update or app shutdown, serialize out to `settings.toml`

You can apply similar concepts to other serialized data. The idea is your serialization class, whether it's a SO or some other plain old C# object, is what you are serializing and then other components act as "activators" to update/recreate objects in your game.

If you had something like a `LevelLoader` that could take `.toml` files and place entities in the world based on file contents you would build that functionality instead of trying to save raw `GameObject` state.

**Comment by ewrogers** [comment]
One thing I had planned on adding in the future was user-customizable serialization via some kind of `ITomlSerializable` interface. This is to cover the cases where you want great control over the serialization process for a certain model/object.

Then exposing some kind of `TomlSerializer` class that you could call some methods on to write various things. A lot of that exists already but it's private because I would have to write a ton more tests and coverage to ensure it works properly.

I would love to, but unfortunately my time is currently split on game dev now so these libraries are in "archive" since I am not currently contributing to them. However if someone wants to fork them or add on their own, go for it.

Just my thoughts on how to extend it further if you really wanted to be able to custom serialize your own objects.
